# If our project had something to compile, it would be C probably
language: c

# Use sudo-less Ubuntu Trusty 14.04.5 LTS
dist: trusty
sudo: required

## Configure, compile and test the project using the four different build types

matrix:
  fast_finish: true

env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release
  - CMAKE_BUILD_TYPE=RelWithDebInfo
  - CMAKE_BUILD_TYPE=MinSizeRel

# Install the dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y cmake lrzip
  - curl -s https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh > cmake-3.12.3-Linux-x86_64.sh
  - sudo mkdir -p /usr/local/cmake-3.12.3
  - sudo bash cmake-3.12.3-Linux-x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local/cmake-3.12.3
  - export PATH="/usr/local/cmake-3.12.3/bin:$PATH"

# Configure the project
before_script:
  - export PROJECT_VERSION=$(grep VERSION "${TRAVIS_BUILD_DIR}/CMakeLists.txt" | awk 'NR==2 {print gensub(/^.*VERSION +([0-9]+(\.[0-9]+){,3}).*$/, "\\1", "g", $0)}')
  - export PROJECT_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d'/' -f 2-)
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..

# Build and install the project
script:
  - cmake --build .
  - sudo cmake --build . --target install
  - |
    if [[ "$CMAKE_BUILD_TYPE" = "Release" ]] && [[ "$TRAVIS_BRANCH" = release/* ]]; then
      export RELEASE_PRERELEASE=YES
      export TRAVIS_TAG=v$PROJECT_VERSION
      git tag --force v$PROJECT_VERSION
    else
      export RELEASE_PRERELEASE=NO
    fi

# Create the packages before deploying
before_deploy:
  - sudo cpack --config CPackConfig.cmake
  - sudo cpack --config CPackSourceConfig.cmake

# Deploy to GitHub Releases
deploy:
  - provider: releases
    api_key:
      secure: "PBeVaGgFOZUZE694cSJEDpe8/XBokJkl1JLI05pzT5vxS64hmqpDTwMSkPjHmlcnqRDNmzShn68auE4fi/EB03n0dB0SRKdAH2BnnDFiSk3h3MmtOmp2kFe8NiXrGBwaCA8pE/0uHXNedd8pdt7nkkiN5qQIHyYwBF7LKWEhvZ6lqtdf2sE7gCt+G6gnm8gq8CCLKe2S5iaiqNGL4ynsOLEdAPsDZbhUK0GieaQavpDFaDlN3G16HAD4M63a+mSHVR7odTn4B81P3gmPa2J3nEguccHC+70nOYHYngVYx41X00zK6eHAxKbtOjKVeTYAEfNQ6bLe+9zu55SknX3BeCBRzGUfVK1DwURvn33nMnWSMbtYVAKoEzH4Rmt1onQyUMmaTCGMX/XbndVZ09hrW99l0Iq77HwpmgOxH/FDiv44t11Hukoi1OWOTAhhnRI73vqnFI7wujgg1RBqyez9ceff5DKCichTfoGj5XJ99ZEIlEmj28t+x4unHd7Igon1aYqK0mIksCnVmcs1LqKIO3m441it0Fm6JsiNDEgNE01e49XKF2xxJwpgLQgJsVy7kWqZ8VOYKktZWKXsUtBgLOjb51s6SyYY5Y2ta09QEnb8d50V8DlXHUuSpWiYKGAKCrLV3EepHisMzpzK90rksfWX0wYkLo3f1RNKW8BPd98="
    file:
      - $PROJECT_NAME-$PROJECT_VERSION-Linux.tar.bz2
      - $PROJECT_NAME-$PROJECT_VERSION-Linux.tar.gz
      - $PROJECT_NAME-$PROJECT_VERSION-Linux.tar.Z
      - $PROJECT_NAME-$PROJECT_VERSION-Linux.zip
      - $PROJECT_NAME-$PROJECT_VERSION-Linux.sh
      - $PROJECT_NAME.tar.bz2
      - $PROJECT_NAME.tar.gz
      - $PROJECT_NAME.tar.Z
      - $PROJECT_NAME.zip
      - $PROJECT_NAME.sh
    skip_cleanup: true
    overwrite: true
    name: "Release $TRAVIS_TAG"
    body: "Automatic release made by Travis CI"
    on:
      branch: master
      condition: $CMAKE_BUILD_TYPE = Release
      tags: true
  - provider: releases
    api_key:
      secure: "PBeVaGgFOZUZE694cSJEDpe8/XBokJkl1JLI05pzT5vxS64hmqpDTwMSkPjHmlcnqRDNmzShn68auE4fi/EB03n0dB0SRKdAH2BnnDFiSk3h3MmtOmp2kFe8NiXrGBwaCA8pE/0uHXNedd8pdt7nkkiN5qQIHyYwBF7LKWEhvZ6lqtdf2sE7gCt+G6gnm8gq8CCLKe2S5iaiqNGL4ynsOLEdAPsDZbhUK0GieaQavpDFaDlN3G16HAD4M63a+mSHVR7odTn4B81P3gmPa2J3nEguccHC+70nOYHYngVYx41X00zK6eHAxKbtOjKVeTYAEfNQ6bLe+9zu55SknX3BeCBRzGUfVK1DwURvn33nMnWSMbtYVAKoEzH4Rmt1onQyUMmaTCGMX/XbndVZ09hrW99l0Iq77HwpmgOxH/FDiv44t11Hukoi1OWOTAhhnRI73vqnFI7wujgg1RBqyez9ceff5DKCichTfoGj5XJ99ZEIlEmj28t+x4unHd7Igon1aYqK0mIksCnVmcs1LqKIO3m441it0Fm6JsiNDEgNE01e49XKF2xxJwpgLQgJsVy7kWqZ8VOYKktZWKXsUtBgLOjb51s6SyYY5Y2ta09QEnb8d50V8DlXHUuSpWiYKGAKCrLV3EepHisMzpzK90rksfWX0wYkLo3f1RNKW8BPd98="
    file:
      - $PROJECT_NAME-$PROJECT_VERSION-Linux.tar.bz2
      - $PROJECT_NAME-$PROJECT_VERSION-Linux.tar.gz
      - $PROJECT_NAME-$PROJECT_VERSION-Linux.tar.Z
      - $PROJECT_NAME-$PROJECT_VERSION-Linux.zip
      - $PROJECT_NAME-$PROJECT_VERSION-Linux.sh
      - $PROJECT_NAME.tar.bz2
      - $PROJECT_NAME.tar.gz
      - $PROJECT_NAME.tar.Z
      - $PROJECT_NAME.zip
      - $PROJECT_NAME.sh
    skip_cleanup: true
    overwrite: true
    name: "Release v$PROJECT_VERSION"
    body: "Automatic release made by Travis CI"
    prerelease: true
    on:
      all_branches: true
      condition: $RELEASE_PRERELEASE = YES
