# If our project had something to compile, it would be C probably
language: c

# Test all the compilers
compiler:
  - gcc
  - clang

# Use sudo-less Ubuntu Trusty 14.04.5 LTS
dist: trusty
sudo: required

# Configure, compile and test the project using the four different build types
env:
- CMAKE_BUILD_TYPE=Debug
- CMAKE_BUILD_TYPE=Release
- CMAKE_BUILD_TYPE=RelWithDebInfo
- CMAKE_BUILD_TYPE=MinSizeRel

# Install some utils
before_install:
- sudo apt-get update
- sudo apt-get install -y xz-utils p7zip

# Install the dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y cmake
  - curl -s https://cmake.org/files/v3.13/cmake-3.13.0-rc2-Linux-x86_64.sh > cmake-3.13.0-rc2-Linux-x86_64.sh
  - sudo bash cmake-3.13.0-rc2-Linux-x86_64.sh --skip-license --prefix /usr

# Configure the project
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..

# Build and install the project
script:
  - cmake --build .
  - sudo cmake --build . --target install
  - sudo cpack --config CPackConfig.cmake
  - sudo cpack --config CPackSourceConfig.cmake

# Create the packages before deploying
before_deploy:
  - sudo cpack --config CPackConfig.cmake
  - sudo cpack --config CPackSourceConfig.cmake
