language: c
dist: trusty
sudo: required
matrix:
  fast_finish: true
env:
- CMAKE_BUILD_TYPE=Debug
- CMAKE_BUILD_TYPE=Release
- CMAKE_BUILD_TYPE=RelWithDebInfo
- CMAKE_BUILD_TYPE=MinSizeRel
install:
- sudo apt-get update
- sudo apt-get install -y cmake lrzip
- curl -s https://cmake.org/files/v3.13/cmake-3.13.0-rc2-Linux-x86_64.sh > cmake-3.13.0-rc2-Linux-x86_64.sh
- sudo mkdir -p /usr/local/cmake-3.13.0-rc2
- sudo bash cmake-3.13.0-rc2-Linux-x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local/cmake-3.13.0-rc2
- export PATH="/usr/local/cmake-3.13.0-rc2/bin:$PATH"
before_script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
script:
- cmake --build .
- sudo cmake --build . --target install
before_deploy:
- sudo cpack --config CPackConfig.cmake
- sudo cpack --config CPackSourceConfig.cmake
- export PROJECT_VERSION=$(grep VERSION "${TRAVIS_BUILD_DIR}/CMakeLists.txt" | awk
  'NR==2 {print gensub(/^.*VERSION +([0-9]+(\.[0-9]+){,3}).*$/, "\\1", "g", $0)}')
- export PROJECT_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d'/' -f 2-)
deploy:
  - provider: releases
    api_key:
      secure: C0AXQsU/a48nE05fCYF3ox9e/NyufSvqBjFnVF8saFuolKPo7+0XVntAAfF01nX1utylpxMzllKZVRlVOiEoR8cLD4cosf6TMILC0sr/HX+jWgShRvpqr4/TdUPe/qXBI6TQUGo/jiSqBKcfMgtnbbkDTs7DExUmGYpgewzd3u3tFlMl7XElRcvdplKn+a52Incpuqralb/SnPEUB61JTzULU5o7H2uOkbF7h43xW5mpWvFL9vqiifeY+wekpz/X2tW8oUYGXE9dthrsyT7tXtcHQw6QIk1wQzNW3QRceC4YXGPQSvqD/s8UJGdBPR6S8IvCJkGfQx17KaF1sDtkv3t7gdEjZC9wCmtYQuFPj0Fdei3N4W4tjFKG8DYpWHIIgYbbaXh+cmTS+5QAsqFWm4VjEdAd3Cl86nm7ywiRFa1tOJ3k1KGGh+SbmkHSXxfU+Z9dIBdJGI4Xr1rMS1edJ0wAK242Oz7BIyaW2imqx6rGtVdpI+VUh/RU0kDFxV4daEr/+FfI4Dbs1XCmELMaq4uWG81g+iQQOMbgtTTDJa3VKtowzDfllF8WCnpjwUn0MW8obXCMkTzwojXLhTrbwydT5o3cFIs5pM58ZCTUHkWZaMiYrPjTS4ro23c69q9RBkuWtAsskwu1efbJrmpZTJNBoI4V/23Divy/lNth+84=
    file:
    - build/$PROJECT_NAME-$PROJECT_VERSION-Linux.tar.bz2
    - build/$PROJECT_NAME-$PROJECT_VERSION-Linux.tar.gz
    - build/$PROJECT_NAME-$PROJECT_VERSION-Linux.tar.Z
    - build/$PROJECT_NAME-$PROJECT_VERSION-Linux.zip
    - build/$PROJECT_NAME-$PROJECT_VERSION-Linux.sh
    - build/$PROJECT_NAME.tar.bz2
    - build/$PROJECT_NAME.tar.gz
    - build/$PROJECT_NAME.tar.Z
    - build/$PROJECT_NAME.zip
    - build/$PROJECT_NAME.sh
    skip_cleanup: true
    overwrite: true
    name: Release $TRAVIS_TAG
    body: Automatic release made by Travis CI
    draft: true
    prerelease: false
    on:
      branch: develop
